name: "base"
channels:
  - conda-forge
dependencies:
  - conda-forge::gdal=3.9.2
  - conda-forge::git
  - pip
  - pip:
    - click
    - cdsapi>=0.7.0
    - dask
    - datetime
    - fsspec
    - gcsfs
    - joblib
    - loguru
    - munch
    - netcdf4
    - numpy==2.1.0
    - pandas
    - planetary-computer
    - pqdm
    - pystac-client
    - python-dotenv
    - pyyaml
    - rasterio==1.3.10
    - rioxarray
    - s3fs
    - scipy
    - stackstac
    - xarray
    - yamale
